site_name: OpenGov.nl
site_url: https://opengov.nl
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - search.suggest
    - search.highlight
  logo: assets/images/icon.svg
  favicon: assets/images/icon.svg
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: contrast
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: contrast
        name: Switch to light mode
  font:
    text: Geist
    code: Geist Mono
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - blog:
      blog_dir: blog
      post_readtime: false
      blog_toc: false
      post_date_format: dd.MM.yyyy
  - blog:
      blog_dir: events
      blog_toc: false
      post_date_format: dd.MM.yyyy
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
extra:
  social:
    - icon: github 
      link: https://github.com/opengov-lab/
    - icon: icai 
      link: https://www.icai.ai/labs/icai-opengov-lab
    - icon: bluesky 
      link: https://bsky.app/profile/opengov.nl
    - icon: linkedin 
      link: https://www.linkedin.com/company/opengov-lab
  generator: false
nav:
  - Team: team.md
  - Partners: partners.md
  - Blog: blog/index.md
  - Events: events/index.md
  - Resources: resources.md
  - Papers: publications.md
  - Contact: contact.md
