authors:
  dgraus:
    name: David Graus
    description: Lab Manager 
    avatar: https://avatars.githubusercontent.com/u/894054?v=4
    url: https://graus.nu
  mmarx:
    name: Maarten Marx
    description: Lab Director
    avatar: https://avatars.githubusercontent.com/u/3773808?s=96&v=4 
